version: 2.1
orbs:
  node: circleci/node@1.1.6

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
jobs:
  build:
    parallelism: 4
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
  test:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout

notify:
  webhooks:
    - url: https://enna0rxjwr3g.x.pipedream.net