# Orb 'circleci/hello-build@0.0.10' resolved to 'circleci/hello-build@0.0.10'
version: 2.1

workflows:
  sign-it:
    jobs:
    - test      
    - approve-adhoc:
        type: approval
        requires:
          - test
      
    - approve-store:
        type: approval
        requires:
          - test
      
    - sign-adhoc:
        requires:
          - approve-adhoc
      
    - sign-store:
        requires:
          - approve-store

  version: 2

jobs:
  test:
    docker:
    - image: circleci/node:10
    steps:
    - run: |
        if [[ `git log -1 --pretty=format:%s ${CIRCLE_SHA1}` == *"[appstore-sign]"* ]]; then
          echo "Use appstore signing"
          export FASTLANE_LANE="appstore"
        else
          echo "Use ad-hoc-sign"
          export FASTLANE_LANE="adhoc"
        fi

  approve-adhoc:
    docker:
    - image: circleci/node:10
    steps:
    - run: echo "hi"

  approve-store:
    docker:
    - image: circleci/node:10
    steps:
    - run: echo "hi"

  sign-adhoc:
    docker:
    - image: circleci/node:10
    steps:
    - run: echo "hi"

  sign-store:
    docker:
    - image: circleci/node:10
    steps:
    - run: echo "hi"
