version: 2.1

workflows:
  monorepo:
    jobs:
      - sample/dummy:
          name: Security go
      - sample/dummy:
          name: API node
      - sample/dummy:
          name: UI node
      - sample/dummy:
          name: Integration
          requires:
            - Security go
            - API node
            - UI node
      - Approval:
          type: approval
          requires:
            - Integration
      - sample/dummy:
          name: Deploy
          requires:
            - Approval

orbs:
  sample:
    jobs: 
      dummy:
        docker:
        - image: circleci/node:10
        steps:
          - run: echo "running"
