version: 2.1


workflows:
  build_test_deploy:
    jobs:
      - build:
          name: Alpha Release On Develop Branch
          filters:
            branches:
              only: develop
      - build:
          name: Beta Release On Release/* Branch
          release_arguments: "-Drelease.version=RC.${CIRCLE_BUILD_NUM}"
          filters:
            branches:
              only: /release\/.*/

jobs:
  build:
    parameters:
      release_arguments:
        type: string
        default: "-Drelease.version=ALPHA.${CIRCLE_BUILD_NUM}"
        description: "This lets a single job be re-used in the workflow with different command execution."
    docker:
    - image: circleci/node:10
    steps:
    - run: |
        echo "Running release task based on branch type"
        echo "i.e.  builder build <<parameters.release_arguments>>"