version: 2.1

workflows:
  build:
    jobs:
      - sample_job
  

jobs:
  sample_job: #single job for example only, these would be 2 uniue jobs with independetn steps.
    parallelism: 3
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hi"
      - run: |
          if [ $CIRCLE_NODE_INDEX -eq 0 ]; then
            sleep 240
          elif [ $CIRCLE_NODE_INDEX -eq 1 ]; then
            exit 1
          elif [ $CIRCLE_NODE_INDEX -eq 2 ]; then
            exit 0
          fi