
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo "Using compare URL: ${CIRCLE_COMPARE_URL}"
      - run: |
          # note, if COMPARE_URL is empty, this runs against full log history
          for folder in `git log --format="" --name-only ${CIRCLE_COMPARE_URL##http*/} | cut -d"/" -f1 | sort -u`; do
             echo $folder
          done
