version: 2.1

orbs:
  recorb:
    executors:
      default:
        macos:  # indicate that we are using the macOS executor
          xcode: 10.0.0
    commands:
      start:
        steps:
          - run: 
              name: Start Quicktime Screencast
              command: |
                cat \<<EOF > ./start_recording.scpt
                tell application "QuickTime Player"
                  set recording to new screen recording
                  tell recording
                    start
                    delay 3
                  end tell
                end tell
                EOF
                osascript ./start_recording.scpt &

      stop:
        steps:
          - run:
              when: always 
              name: Stop Quicktime Screencast
              command: |
                cat \<<EOF > ./stop_recording.scpt              
                tell application "QuickTime Player"
                  set recording to first document
                  tell recording
                    pause
                    set current_path to do shell script "pwd"
                    set file_path to current_path & "/testrecording.mov"
                    save in (file_path as POSIX file)
                    -- export in ("../testrecording.mov" as POSIX file) using settings preset "480p"
                    stop
                    return "Test recording saved to " & file_path
                    close
                  end tell
                end tell
                EOF
                osascript ./stop_recording.scpt
          - store_artifacts:
              path: testrecording.mov
              destination: testrecording.mov
    jobs:
      wrap:
        parameters:
          steps:
            type: steps
            description: steps to be captured by recordin
        executor: default
        steps:
          - start
          - steps: <<parameters.steps>>
          - stop



workflows:
  build-deploy:
    jobs:
      - recorb/wrap:
          steps:
            - run: open -a safari https://edwardawebb.com