version: 2.1

orbs:
  jira: circleci/jira@dev:RC-1


workflows:
  build-deploy:
    jobs:
      - component-A
      - component-B
      - integration:
          requires:
          - component-A
          - component-B
      - deploy:
          name: Dev East
          requires: 
          - integration
      - deploy:
          name: Test East
          requires:
          - Dev East
          environment-type: testing
      - hold:
          name: Verify
          requires:
          - Test East
          type: approval
      - deploy:
          name: Prod East
          requires:
          - Verify
          environment-type: production

jobs:
  component-A:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 0
      - jira/notify

  component-B: #this job just ensutes that integration job get a higher component-B number than lint
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 2
      - jira/notify

  integration:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify

  deploy:
    parameters:
      environment-type:
        type: string
        default: development
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify:
          job_type: deployment
          environment_type: <<parameters.environment-type>>

