version: 2.1
orbs:
  webhook: eddiewebb/webhook@dev:local
workflows:
  stress_stats:
    jobs:
      build:
        docker:
          - image: circleci/node:10
        working_directory: ~/repo
        steps:
            - run: echo "hi"
            - webhook/notify:
                endpoint: "https://postb.in/7RFuDLos"
notify:
  webhooks:
    - url: http://requestbin.fullcontact.com/1f6b6vc1