
version: 2
jobs:
  build:
    # This job looks in a specific subfolder for any changes
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo "Using compare URL: ${CIRCLE_COMPARE_URL}"

  deploy:
    # This job looks in a specific subfolder for any changes
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - run: echo "oh bother"
    deploy:
      - checkout
      - run: |
          echo "Using compare URL: ${CIRCLE_COMPARE_URL}"
      - run:
          name: Slow stuff
          command: |
            sleep 120


workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
