
version: 2.1

orbs:
  eks: circleci/aws-eks@0.1.0
  kubernetes: circleci/kubernetes@0.3.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - publish-docker:
      - eks/create-cluster:
          cluster-name: dynamic-cluster-${CIRCLE_WORKFLOW_ID}

      - test-cluster:
          cluster-name: dynamic-cluster-${CIRCLE_WORKFLOW_ID}
          requires:
            - eks/create-cluster
            - publish-docker

      - eks/delete-cluster:
          cluster-name: dynamic-cluster-${CIRCLE_WORKFLOW_ID}
          requires:
            - test-cluster

jobs:
  publish-docker:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
      - checkout
      - echo "Generating image from lastest code....."


      
  test-cluster:
    executor: eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - eks/update-kubeconfig-with-authenticator:
          cluster-name: dynamic-cluster-${CIRCLE_WORKFLOW_ID}
      - run:
          command: |
            kubectl get services
          name: Test cluster