version: 2
jobs:
  build:
    machine:
      image: windows-server-2019
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
    - checkout
    - run:
        name: Run integration tests
        command: |
          "set PATH=%PATH%;C:\Users\circleci\.local\bin \r\n"
          "echo %PATH% \r\n"
          "where state \r\n"
          "state run integration-tests \r\n"
        shell: cmd.exe