version: 2.1

parameters:
  orb_version:
    default: "latest"
    type: string

orbs:
  common: eddiewebb/common_tasks@dev:pull/2-67cd95d4af5bf8c96a15e8adb1803af71213a8a9

workflows:
  basic:
    jobs:
      - common/common_task:
          task-name: demo-task
          post-steps:
            # run 2nd invocation in same container
            - common/run_shared_task:
                task-name: demo-task
                