version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
    - checkout
    - run:
        name: Run integration tests
        command: |
          echo %PATH% \r
          where state \r
          state run integration-tests \r
        shell: cmd.exe
