version: 2.1

orbs:
  common: eddiewebb/common_tasks@0.1.0

parameters:
  task_name:
    default: "demo-task"
    type: string

jobs:
  build:
    docker:
    - image: circleci/node:10
    steps:
    - run: echo "<<pipeline.parameters.task_name>>"
    - common/run_shared_task:
          task-name: <<pipeline.parameters.task_name>>