version: 2.1

orbs:
  inline-orb:
    commands:
      say-hello:
        parameters:
          to:
            type: string
            default: "world"
        steps:
          - run: Hello <<parameters.to>>

    jobs:
      inline-job:
        docker:
          - image: circleci\node:10
        steps:
          - say-hello
        parameters:
          to:
            type: string
            default: "world"


workflows:
  workflow_a:
    jobs:
      - inline-orb/inline-job
      - inline-orb/inline-job:
          to: Eddie
