version: 2.1

orbs:
  common: eddiewebb/common_tasks@dev:eddie

workflows:
  basic:
    jobs:
      - common/common_task:
          task-name: demo-task
          pre-steps: 
            - run: sleep 60
      - common/common_task:
          task-name: demo-task-with-parameters
          pre-steps:
            - run: echo "export SOME_VAR=value" >> $BASH_ENV
