version: 2
jobs:
  test:
    docker:
    - image: circleci\node:10
    steps:
    - run:
        command: echo "hi"
  sign-adhoc:
    docker:
    - image: circleci\node:10
    steps:
    - run:
        command: echo "hi"
  sign-store:
    docker:
    - image: circleci\node:10
    steps:
    - run:
        command: echo "hi"
workflows:
  sign-it:
    jobs:
    - test
    - approve-adhoc:
        type: approval
        requires:
        - test
    - approve-store:
        type: approval
        requires:
        - test
    - sign-adhoc:
        requires:
        - approve-adhoc
    - sign-store:
        requires:
        - approve-store
  version: 2

# Original config.yml file:
# # Orb 'circleci/hello-build@0.0.10' resolved to 'circleci/hello-build@0.0.10'
# version: 2.1
# 
# workflows:
#   sign-it:
#     jobs:
#     - test      
#     - approve-adhoc:
#         type: approval
#         requires:
#           - test
#       
#     - approve-store:
#         type: approval
#         requires:
#           - test
#       
#     - sign-adhoc:
#         requires:
#           - approve-adhoc
#       
#     - sign-store:
#         requires:
#           - approve-store
# 
#   version: 2
# 
# jobs:
#   test:
#     docker:
#     - image: circleci\\node:10
#     steps:
#     - run: echo \"hi\"
# 
#   approve-adhoc:
#     docker:
#     - image: circleci\\node:10
#     steps:
#     - run: echo \"hi\"
# 
#   approve-store:
#     docker:
#     - image: circleci\\node:10
#     steps:
#     - run: echo \"hi\"
# 
#   sign-adhoc:
#     docker:
#     - image: circleci\\node:10
#     steps:
#     - run: echo \"hi\"
# 
#   sign-store:
#     docker:
#     - image: circleci\\node:10
#     steps:
#     - run: echo \"hi\"
