orbs:
  win: circleci/windows@2.4.0
  kubernetes: circleci/kubernetes@0.9.0
  aws-eks: circleci/aws-eks@0.2.6
  aws-ecr: circleci/aws-ecr@6.7.1

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    steps: 
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          aws-access-key-id: SI_RAFA_GLOBAL_ACCESS_KEY
          aws-secret-access-key: SI_RAFA_GLOBAL_SECRET_KEY
          checkout: false
          create-repo: true
          dockerfile: 'Dockerfile.rc'
          path: './rc-service/Source'
          region: SI_RAFA_GLOBAL_REGION
          repo: '${AWS_ECR_REPO}'
          tag: 'latest,${GIT_HASH}'