version: 2.0
jobs:
  build:
    resource_class: large
    macos:
      xcode: '9.0'
    steps:
    - checkout
    - run: |
        ls
        vm_stat
        top -l 1 | grep PhysMem:
        system_profiler SPHardwareDataType | grep "  Memory:"
        system_profiler SPHardwareDataType | grep Cores:
        system_profiler SPHardwareDataType | grep Processors:
workflows:
  version: 2
  workflow:
    jobs:
    - build
