version: 2.1

parameters:
  pass_by_build:
    default: "default"
    type: string

jobs:
  build:
    docker:
    - image: circleci/node:10
    parallelism: 4
    steps:
    - run: echo "<<pipeline.parameters.pass_by_build>>"