version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - restore_cache:
          keys:
            - storage-test
      - run: ls -lah
      - run: dd if=/dev/zero of=./bigcache.file bs=4k iflag=fullblock,count_bytes count=200M
      - run: ls -lah
      - save_cache:
          paths:
            - bigcache.file
          key: storage-test