version: 2.1

parameters:
  publish_target:
    default: "" #empty values considered FALSEY
    type: string

workflows:
  build:
    unless: <<pipeline.parameters.publish_target>>
    jobs:
      - sample_job:
          name: Build It
  share:
    when: <<pipeline.parameters.publish_target>>
    jobs:
      - sample_job:
          name: Share It

jobs:
  sample_job: #single job for example only, these would be 2 uniue jobs with independetn steps.
    docker:
      - image: cimg/base:latest
    steps:
      - run: echo "hi"