workflows:
  version: 2
  build-deploy:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-browsers
    working_directory: ~/repo
    steps:
      - run: git clone https://github.com/cBioPortal/cbioportal-frontend.git .
      - run: npm install
      - run: cat package-lock.json | grep 'http:' || echo "no non-ssl urls found"
      - run: mkdir artifacts && cp package-lock.json artifacts/
      - store_artifacts:
            path: artifacts
