version: 2.1

orbs:
  hello: circleci/hello-build@0.0.13

workflows:
  version: 2
  build_deploy:
    jobs:
      - my_job

jobs:
  my_job:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true

    steps:
      - hello/circleci-env-highlights
      - run: |
          sudo ls -la /var/lib/docker
          sudo ls -la /var/lib/docker/volumes
          sudo ls -la /var/lib/docker/image
      - run: |
          sudo mkdir -p /var/lib/docker/mygit
          echo "im here" >> /var/lib/docker/mygit/index
      - run: |
          sudo ls -la /var/lib/docker
          sudo ls -la /var/lib/docker/volumes
          sudo ls -la /var/lib/docker/image
          cat /var/lib/docker/mygit/index
