version: 2.1

orbs:
  jira: circleci/jira@dev:ccd6b20

workflows:
  build-deploy:
    jobs:
      - component-B
      - hold:
          name: Dev East
          type: approval
          requires:
          - component-B
      - deploy:
          name: Test East
          requires:
          - Dev East
          environment-type: testing
          # test context
          context: AWS-test
      - deploy:
          name: Prod East
          requires:
          - Test East
          environment-type: production
          # prod context
          context: AWS-prod

jobs:
  component-A: #this job just ensutes that integration job get a higher component-B number than lint
    docker:
      - image: cimg/node:10.18
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 0
      - jira/notify
  component-B: #this job just ensutes that integration job get a higher component-B number than lint
    docker:
      - image: cimg/node:10.18
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 1
      - jira/notify

  integration:
    docker:
      - image: cimg/node:10.18
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify

  deploy:
    parameters:
      environment-type:
        type: string
        default: development
    docker:
      - image: cimg/node:10.18
    working_directory: ~/repo
    steps:
      - checkout
      # circleCI will mask known variables from project or context.
      - run: echo "${SAME_VARIABLE}"
      # simple switch to demonstrate that dev, test and deploy are given unique values
      - run: |
          case "${SAME_VARIABLE}" in
            "project")
              echo "proj level variable"
              ;;
            "test")
              echo "tes-t level variable"
              ;;
            "production")
              echo "pro-d level variable"
              ;;
            *)
              echo "variable unknown"
              ;;
            esac
      - jira/notify:
          job_type: deployment
          environment_type: <<parameters.environment-type>>
          