version: 2.1
orbs:
  hello: circleci/hello-build@volatile
workflows:
  stress_stats:
    jobs:
      - hello/hello-build:
          post-steps:
            - run: echo "hi"
notify:
  webhooks:
    - url: http://requestbin.fullcontact.com/1f6b6vc1