version: 2.1
workflows:
  build-deploy:
    jobs:
      - fail-fast
      - ensure-fail-first
      - build-job:
          requires:
          - ensure-fail-first
      - deploy:
          name: Dev East
          requires: 
          - build-job
      - deploy:
          name: Test East
          requires:
          - Dev East
          environment-type: testing
      - deploy:
          name: Prod East
          requires:
          - Test East
          environment-type: production

orbs:
  jira: eddiewebb/burps@dev:build-zero

jobs:
  fail-fast:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 1
      - jira/notify

  ensure-fail-first: #this job just ensutes that build-job job get a higher build number than fail-fast
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 2
      - jira/notify

  build-job:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify

  deploy:
    parameters:
      environment-type:
        type: string
        default: development
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify:
          job_type: deployment
          environment_type: <<parameters.environment-type>>

