version: 2.1

parameters:
  publish_target:
    default: "" #empty values considered FALSEY
    type: string

workflows:
  build:
    unless: <<pipeline.parameters.publish_target>>
    jobs:
      - sample_job:
          name: Build It
  share:
    when: <<pipeline.parameters.publish_target>>
    jobs:
      - sample_job:
          name: Share It

jobs:
  sample_job: #single job for example only, these would be 2 uniue jobs with independetn steps.
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hi"
      - run: |
          echo "pipeline.id: ${pipeline.id:-UNDEFINED}"
          echo "pipeline.number: ${pipeline.number:-UNDEFINED}"
          echo "pipeline.project_slug: ${pipeline.project_slug:-UNDEFINED}"
          echo "pipeline.created_timestamp: ${pipeline.created_timestamp:-UNDEFINED}"
          echo "pipeline.trigger.branch: ${pipeline.trigger.branch:-UNDEFINED}"
          echo "pipeline.trigger.rerun_of: ${pipeline.trigger.rerun_of:-UNDEFINED}"
          echo "pipeline.trigger.tag: ${pipeline.trigger.tag:-UNDEFINED}"
          echo "pipeline.trigger.actor: ${pipeline.trigger.actor:-UNDEFINED}"
          echo "pipeline.trigger.end_sha: ${pipeline.trigger.end_sha:-UNDEFINED}"
          echo "pipeline.trigger.begin_sha: ${pipeline.trigger.begin_sha:-UNDEFINED}"
          echo "pipeline.pull_request.draft: ${pipeline.pull_request.draft:-UNDEFINED}"
          echo "pipeline.pull_request.number: ${pipeline.pull_request.number:-UNDEFINED}"
          echo "pipeline.pull_request.url: ${pipeline.pull_request.url:-UNDEFINED}"
          echo "pipeline.pull_request.source_branch: ${pipeline.pull_request.source_branch:-UNDEFINED}"
          echo "pipeline.pull_request.source_repo: ${pipeline.pull_request.source_repo:-UNDEFINED}"
          echo "pipeline.pull_request.target_branch: ${pipeline.pull_request.target_branch:-UNDEFINED}"
          echo "pipeline.pull_request.target_repo: ${pipeline.pull_request.target_repo:-UNDEFINED}"
          echo "pipeline.pull_request.fork: ${pipeline.pull_request.fork:-UNDEFINED}"
          echo "pipeline.project.default_branch: ${pipeline.project.default_branch:-UNDEFINED}"
          echo "pipeline.project.repo_name: ${pipeline.project.repo_name:-UNDEFINED}"
          echo "pipeline.project.organization_name: ${pipeline.project.organization_name:-UNDEFINED}"
          echo "pipeline.project.type: ${pipeline.project.type:-UNDEFINED}"