version: 2.1
orbs:
  hello: circleci/hello-build@0.0.7

workflows:
  stress_stats:
    jobs:
      - hello/hello-build:
          name: test
      - hello/hello-build:
          name: stage
          requires: [test]
      - hold:
          type: approval
          requires: [stage]
      - hello/hello-build:
          name: prod
          requires: [hold]
      - hello/hello-build:
          name: done
          requires: [stage, prod]
