version: 2.1

parameters:
  publish_target:
    default: "" #empty values considered FALSEY
    type: string

jobs:
  build:
    docker:
      - image: cimg/base:latest
    steps:
      - run: echo "build and test"
      - when: 
          condition: <<pipeline.parameters.publish_target>>
          steps:
            - run:
                name: Publish Ad-hoc .ipa to testflight
                command: echo "Publishing <<pipeline.parameters.publish_target>> to testflight. "

    
                