
version: 2
jobs:
  build:
    # This job looks in a specific subfolder for any changes
    machine:
      docker_layer_caching: true
    steps:
      - run: mkdir results
      - run: docker images --format '{{.ID}} {{.Repository}} {{.Tag}}' > results/images
      - run: |
          while read IMAGE;do
            echo "history for ${IMAGE}"
            hash=`echo ${IMAGE} | cut -f1 -d" "`
            docker history ${hash}
          done<results/images
      - run: docker volumes ls > results/volumes
      - run: |
          while read IMAGE;do
            echo "history for ${IMAGE}"
            hash=`docker volume ls --format '{{.Name}} {{.Driver}}' | cut -f1 -d" "`
            docker volume inspect ${hash}
          done<results/volumes
      - store_artifacts:
          path: results
