version: 2.1
workflows:
  build-deploy:
    jobs:
      - fail-fast
      - ensure-fail-first
      - build-job:
          requires:
          - ensure-fail-first

orbs:
  jira: eddiewebb/burps@dev:eddie-level

jobs:
  fail-fast:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: exit 0
      - jira/notify

  ensure-fail-first: #this job just ensutes that build-job job get a higher build number
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sleep 2
      - jira/notify:
          job_type: deployment

  build-job:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify
