version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run: 
          name: Install Docker Machine
          command: |
            base=https://github.com/docker/machine/releases/download/v0.14.0 &&
            curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
            sudo install /tmp/docker-machine /usr/local/bin/docker-machine
      - run:
          name: Create Remote Host
          command: |
            docker-machine create ${CIRCLE_WORKFLOW_ID} --driver amazonec2 --amazonec2-subnet-id ${AWS_SUBNET_ID} --amazonec2-vpc-id ${AWS_VPC_ID} --amazonec2-region us-east-2
            eval $(docker-machine env ${CIRCLE_WORKFLOW_ID} --shell bash
      - run:
          name: Docker Build
          command: |
            eval $(docker-machine env ${CIRCLE_WORKFLOW_ID} --shell bash
            docker build .

      - run:
          name: Docker Cleanup
          when: always
          command: |
            docker-machine rm ${CIRCLE_WORKFLOW_ID}

