# Orb 'circleci/hello-build@0.0.10' resolved to 'circleci/hello-build@0.0.10'
version: 2
jobs:
  hello-build/hello-build:
    docker:
    - image: bash:4.4.19
    steps:
    - run:
        command: echo "Hello eddie"
    - run:
        command: |-
          echo "TRIGGERER: ${CIRCLE_USERNAME}"
          echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
          echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
          echo "BRANCH: ${CIRCLE_BRANCH}"
          echo "RUNNING JOB: ${CIRCLE_JOB}"
          echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
          echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
        name: Show some of the CircleCI runtime env vars
    - run:
        command: |-
          echo "uname:" $(uname -a)
          echo "arch: " $(uname -m)
        name: Show system information
workflows:
  Hello Workflow:
    jobs:
    - hello-build/hello-build
  version: 2

# Original config.yml file:
# # project uses 2.0 - see .git/hooks/pre-commit
# version: 2.1
# 
# orbs:
#   hello-build: circleci/hello-build@0.0.10
# 
# workflows:
#   Hello Workflow:
#     jobs:
#     - hello-build/hello-build:
#         to: eddie
