version: 2
jobs:
  build:
    machine:
      image: windows-server-2019
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
    - checkout
    - run:
        command: echo 'Hello, Windows'
workflows:
  version: 2
  workflow:
    jobs:
    - build