version: 2.1

orbs:
  hello-build: circleci/hello-build@0.0.13


workflows:
  build-deploy:
    jobs:
      - hello-build/hello-build:
          post-steps:
          - run:
              name: sleep
              command: sleep 100
          - run:
              name: cleanup
              command: echo "I ran"
              when: always