version: 2.1
orbs:
  webhook: eddiewebb/webhook@volatile

jobs:
  build:
        docker:
          - image: circleci/node:10
        working_directory: ~/repo
        steps:
            - run: echo "hi"
            - webhook/notify:
                endpoint: "https://postb.in/7RFuDLos"
notify:
  webhooks:
    - url: https://requestbin.fullcontact.com/1f6b6vc1
    