version: 2.1


workflows:
  build_test_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
    - image: circleci/node:10
    steps:
    - run: |
        cd /tmp 
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok*
        nohup ./ngrok http 8080 &
        NHOST=`curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p'`
        echo "Ngrok exposed publicly as $NHOST, starting gotty presently"
        wget https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz
        tar -xzf gotty*
        ./gotty -p 8080 -w --once bash
        