version: 2.1

parameters:
  publish_target:
    default: "" #empty values considered FALSEY
    type: string

workflows:
  build:
    unless: <<pipeline.parameters.publish_target>>
    jobs:
      - sample_job:
          name: Build It
  share:
    when: <<pipeline.parameters.publish_target>>
    jobs:
      - sample_job:
          name: Share It

jobs:
  sample_job: #single job for example only, these would be 2 uniue jobs with independetn steps.
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hi"
      - run: |
          echo "pipeline.id: << pipeline.id >> "
          echo "pipeline.number: << pipeline.number >> "
          echo "pipeline.project_slug: << pipeline.project_slug >> "
          echo "pipeline.created_timestamp: << pipeline.created_timestamp >> "
          echo "pipeline.trigger.branch: << pipeline.trigger.branch >> "
          echo "pipeline.trigger.rerun_of: << pipeline.trigger.rerun_of >> "
          echo "pipeline.trigger.tag: << pipeline.trigger.tag >> "
          echo "pipeline.trigger.actor: << pipeline.trigger.actor >> "
          echo "pipeline.trigger.end_sha: << pipeline.trigger.end_sha >> "
          echo "pipeline.trigger.begin_sha: << pipeline.trigger.begin_sha >> "
          echo "pipeline.pull_request.draft: << pipeline.pull_request.draft >> "
          echo "pipeline.pull_request.number: << pipeline.pull_request.number >> "
          echo "pipeline.pull_request.url: << pipeline.pull_request.url >> "
          echo "pipeline.pull_request.source_branch: << pipeline.pull_request.source_branch >> "
          echo "pipeline.pull_request.source_repo: << pipeline.pull_request.source_repo >> "
          echo "pipeline.pull_request.target_branch: << pipeline.pull_request.target_branch >> "
          echo "pipeline.pull_request.target_repo: << pipeline.pull_request.target_repo >> "
          echo "pipeline.pull_request.fork: << pipeline.pull_request.fork >> "
          echo "pipeline.project.default_branch: << pipeline.project.default_branch >> "
          echo "pipeline.project.repo_name: << pipeline.project.repo_name >> "
          echo "pipeline.project.organization_name: << pipeline.project.organization_name >> "
          echo "pipeline.project.type: << pipeline.project.type >> "
          