version: 2.1

commands:
  release:
    description: "Builds the ATO cockpit assets"
    parameters:
      task:
        type: string
      save_cache:
        type: boolean
        default: false
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package-lock.json" }}
            - deps
      - run:
          name: Deps
          command: npm install
      - when:
          condition:  << parameters.save_cache >>
          steps:
            - save_cache:
                key: deps-{{ checksum "package-lock.json" }}
                paths:
                  - node_modules
      - run:
          name: compile
          command: npm run staging
      - run:
          name: package
          command: tar czf ato-cockpit-<< parameters.task >>.tgz -C dist .
      - persist_to_workspace:
          root: ./
          paths:
            - ato-cockpit-staging.tgz

executors:
  build:
    docker:
      - image: circleci/node:10

jobs:
  build_staging:
    executor: build
    steps:
      - release:
          task: staging
          save_cache: true
  build_production:
    executor: build
    steps:
      - release:
          task: production
          save_cache: false

workflows:
  version: 2
  build_and_deploy_staging:
    jobs:
      - build_staging