version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-27-alpha
    working_directory: ~/repo
    environment:
    - TERM: dumb
    - JVM_OPTS: -Xmx4096m
    - _JAVA_OPTIONS: -Xmx4096m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
        -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
    - GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m
        -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.daemon=false
    resource_class: large
    steps:
    - checkout
    - run:
        name: Checkout submodules
        command: |
          git submodule sync
          git submodule update --init
          git submodule foreach --recursive git checkout develop
    - run:
        name: JVM Memory Settings and Version
        command: java -XshowSettings:vm -version
    - run:
        name: Install Android NDK
        command: source ./circleCiEnvironmentSetup.sh && getAndroidNDK
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
    - run:
        name: Unit Tests
        command: ./gradlew testProdReleaseUnitTest --no-daemon --max-workers 2
workflows:
  version: 2
  workflow:
    jobs:
    - build
    