version: 2.1

orbs:
  common: eddiewebb/common_tasks@0.1.0

parameters:
  pass_by_build:
    default: "default"
    type: string

jobs:
  build:
    docker:
    - image: circleci/node:10
    steps:
    - run: echo "<<pipeline.parameters.pass_by_build>>"
    - common/run_shared_task:
          task-name: demo-task