version: 2.1

orbs:
  jira: circleci/jira@dev:02deb17

workflows:
  build-deploy:
    jobs:
      - component-B

      # The deploy jobs below use the same steps/execution, but different vaalues of `SAME_VARIABLE`
      - deploy:
          name: Dev East
          requires: 
          - component-B
          # no context provided, will use project level value
      - deploy:
          name: Test East
          requires:
          - Dev East
          environment-type: testing
          # test context
          context: AWS-test
      - deploy:
          name: Prod East
          requires:
          - Test East
          environment-type: production
          # prod context
          context: AWS-prod

jobs:
  component-B: #this job just ensutes that integration job get a higher component-B number than lint
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "<<pipeline.number>>"
      - run: echo " <<pipeline.number>> "
      - jira/notify

  integration:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hi Jira"
      - jira/notify

  deploy:
    parameters:
      environment-type:
        type: string
        default: development
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # circleCI will mask known variables from project or context.
      - run: echo "${SAME_VARIABLE}"
      # simple switch to demonstrate that dev, test and deploy are given unique values
      - run: |
          case "${SAME_VARIABLE}" in
            "project")
              echo "proj level variable"
              ;;
            "test")
              echo "tes-t level variable"
              ;;
            "production")
              echo "pro-d level variable"
              ;;
            *)
              echo "variable unknown"
              ;;
            esac
      - jira/notify:
          job_type: deployment
          environment_type: <<parameters.environment-type>>
          