
version: 2
jobs:
  build:
    # This job looks in a specific subfolder for any changes
    docker:
      - image: circleci/python:2-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo "Using compare URL: ${CIRCLE_COMPARE_URL}"
      - run:
          name: Build any top-level proj_ directories
          command: |
            # note, if COMPARE_URL is empty, this runs against full log history
            PATTERN=proj_
            for folder in `git log --format="" --name-only ${CIRCLE_COMPARE_URL##http*/} | grep $PATTERN | cut -d"/" -f1 | sort -u`; do
               echo $folder
               cat $folder/message #this would be a call to specific testing, etc on changed directory
            done
      - run:
          name: Build any subdirectories in cookbooks folder
          command: |
            # note, if COMPARE_URL is empty, this runs against full log history
            PARENT=cookbooks
            for folder in `git log --format="" --name-only ${CIRCLE_COMPARE_URL##http*/} | grep $PARENT | cut -d"/" -f2 | sort -u`; do
               echo $PARENT/$folder
               cat $PARENT/$folder/message  #this would be a call to specific testing, etc on changed directory
            done
