version: 2.1

orbs:
  hello: circleci/hello-build@0.0.13

workflows:
  version: 2
  build_deploy:
    jobs:
      - my_job

jobs:
  my_job:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true

    steps:
      - hello/circleci-env-highlights
