version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - run: |
          echo ${KEY} | base64 --decode > key.pem
          chmod 0600 key.pem
          ssh-keygen -y -e -f key.pem